### ISSUE TITLE
Bump to node.js 16

### ISSUE THREAD

**Issue by wasamasa** [cask/setup-cask#26]
I'm using this action for Circe and ran into the following warning today:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: conao3/setup-cask@master, actions/checkout@v2

Bumping to node.js 16 shouldn't be hard, but I'm far from a JS expert to tell what the effects of it would be.

**Comment by conao3** [comment]
@wasamasa 
Thanks for reporting this!
#27 from @jcs090218 is merged, so please try again and check this action work as expected.

**Comment by wasamasa** [comment]
Thanks, the warning is gone now. Builds work as usual.
